# Generated by Django 5.2.15 on 2026-06-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0003_alter_profile_user_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='cvu',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
    ]
