# Generated by Django 5.2.15 on 2026-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0004_wallet_alias_wallet_cvu'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='ARS', max_length=3),
        ),
    ]
