# Generated by Django 5.2.15 on 2026-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0005_wallet_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='transtaction',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
